name: Angels and Viet
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5744905637111515
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8590784757398069
  lightness: 0.18697154964320362
  saturation: 0.2322935862466693
  rhythmicContrast: 0.14180246670730412
purpose: []
